### ISSUE TITLE
model nestedunet, attunet "TypeError: empty()"

### ISSUE THREAD

**Issue by nguyenduongZ** [KhoiDOO/autoencoder#9]
![image](https://github.com/KhoiDOO/DecodeItAll/assets/116706467/ca8b7e09-8208-4506-ab26-1114a2a5c3c5)
![image](https://github.com/KhoiDOO/DecodeItAll/assets/116706467/0a45411c-6d6a-428e-94d2-0746a0cfdf0f)
![image](https://github.com/KhoiDOO/DecodeItAll/assets/116706467/91ea4c31-ac94-4a87-9485-91cbd04cef78)
![image](https://github.com/KhoiDOO/DecodeItAll/assets/116706467/e364fff6-8226-4701-9b23-03f915eb4119)

**Comment by KhoiDOO** [comment]
I have rechecked the code implementation for NestUnet, the ```init_channel``` param should be an integer instead of a False boolean shown above. This may be my fault of copying it several times from notebooks to notebooks.

Now the problem is solved, the issue is closed without any further comments.
